name: Test

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  gcc:
    runs-on: ubuntu-latest
    container:
      image: igorfreire/gnuradio-oot-dev:3.9.4-ubuntu-focal
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: apt update && apt install -y libsndfile1-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: cd ${{github.workspace}}/build && ctest -C ${{env.BUILD_TYPE}} -VV
  clang:
    runs-on: ubuntu-latest
    container:
      image: igorfreire/gnuradio-oot-dev:3.9.4-ubuntu-focal
    env:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt update && apt install -y libsndfile1-dev clang
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: cd ${{github.workspace}}/build && ctest -C ${{env.BUILD_TYPE}} -VV
